# fly.toml app configuration file generated for cibo-t0-r1 on 2023-11-11T19:28:17-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cibo-t0-r1"
primary_region = "lax"

[build]

[env]
  DISCORDRB_NONACL = "false"
  DISCO_APP_ID = "1170256304900689951"
  DISCO_DESIRED_PERMS = "17637283843072"
  DISCO_INVITE_URL = "https://discordapp.com/oauth2/authorize?client_id=1170256304900689951&scope=bot&permissions=17637283843072"
  DISCO_OWNER_ID = "280110792953692160"
  DISCO_OWNER_USERNAME = "reactivator"
  DISCO_PUBLIC_KEY = "958ebc4bbae827122535024186687af52eb773b6862cd75fed82eb0dbf6adefc"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
